### ISSUE TITLE
About loss

### ISSUE THREAD

**Issue by Lxy85** [Dynmi/AlexNet#11]
Hi,I used a face dataset with a total of 100 categories, each category is 5 pictures, but the loss has been hovering around 6 during the training process, and the batchsize and epoch are modified, but it still cannot be reduced.

**Comment by Dynmi** [comment]
Hi, Lyx85. Your dataset is so tiny that it couldn't make AlexNet work...

**Comment by Dynmi** [comment]
You can compare it with ImageNet...

**Comment by Lxy85** [comment]
Thank you
