### ISSUE TITLE
能提供一下训练数据和训练模型吗？

### ISSUE THREAD

**Issue by xy815661276** [Dynmi/AlexNet#3]
我是新手，用了你的代码，但是训练数据的时候老是会出错，可以提供一下你用的训练数据吗？谢谢

**Comment by Dynmi** [comment]
首先，这个模型结构是已经搭好的。但是一个好的预训练权重还没给出来，因为这个训练耗时会比较长。
我很快会给出一个预训练模型和使用方法。
至于你说的碰到错误，你试一下clone最新版本再训练，目前训练过程可能会遇到梯度消失的问题，我会很快解决。

至于训练用的测试数据，我一会儿会在readme写出来。

@xy815661276

**Comment by xy815661276** [comment]
好的，谢谢。
我使用一个数据集测试，数据集里面有5个花的类别。图片大小224*224，按照readme里面的提示来训练。
`./alexnet train -batchsize 5 -epochs 1000 -save ./alexnet.weights`
image.list也是按照要求来的。但是训练的时候，会提示错误：
`!!!!!!!!!!!!!!!!!!!!!!!!!!!!Forward: fc2 error !!! -72.577286`

**Comment by Dynmi** [comment]
如果分类的类别数为5的话，建议修改这里https://github.com/Dynmi/AlexNet/blob/master/src/alexnet.h#L62 为5。

你遇到的这个error是指前向传播的fc2层的输出的绝对值太大，我认为应该是训练导致了某一部分权重的绝对值太大，所以在fc2层的输出的绝对值太大了。这可能是梯度爆炸的问题，我目前还没有做针对这些问题的适配，后面很快会将这些problem解决。如果感兴趣的话你可以调一下代码然后PR上来：D

@xy815661276

**Comment by xy815661276** [comment]
我是跑在linux，直接make的，我也不知道怎么调 :( ，还有我把output layer改成5后
`./alexnet train -batchsize 5 -epochs 1000 -save ./alexnet.weights`
然后又遇到错误：
`alexnet: ./src/alexnet.c:133: argmax: Assertion `idx!=-1' failed.`
这个模型只能训练imageNet里面的数据吗？那个数据量实在是太大了，所以我想用一个小一点的训练集试试模型。

**Comment by Dynmi** [comment]
1. ```alexnet: ./src/alexnet.c:133: argmax: Assertion idx!=-1' failed.```这个错误应该和前面一样是梯度爆炸的问题，我很快会适配好这些问题。你可以用小的数据集来尝试，可以自己改一下模型结构，改alexnet.h文件里的宏定义就可以。

2. 一个小建议：训练神经网络时，batch size最好设置为4的倍数。

**Comment by Joejwu** [comment]
你好，我在自己的虚拟机(ubuntu)以及学校的服务器(centos)上跑都会出现段错误，但是我也实在不知道怎么去改，想问一下这是为啥？谢谢!

**Comment by Joejwu** [comment]
![image](https://user-images.githubusercontent.com/46843978/108821830-2b60c200-75f9-11eb-8a92-3a73491338b6.png)
如图所示！基础较差，实在不懂！

**Comment by Joejwu** [comment]
所以想问一下现在有预训练权重了吗？一直出现段错误，不知从何改起！
![Uploading image.png…]()

**Comment by Mrsun0** [comment]
请问创建image.list的时候那个cs命令是什么命令啊？找了半天没有这个命令

**Comment by Dynmi** [comment]
> 请问创建image.list的时候那个cs命令是什么命令啊？找了半天没有这个命令

@mikecovlee

**Comment by Lxy85** [comment]
您好，我使用的编译是waf,代码会出现很多error,是因为不是cmake的原因吗

**Comment by xy815661276** [comment]
已经关闭，有需要请自己打开新的issue
