### ISSUE TITLE
Bug in resize_image

### ISSUE THREAD

**Issue by mjc0608** [Dynmi/AlexNet#7]
In data.c, Line 123 freed the resized image, which will be accessed later during training/inference.

Line 121 - 123 should be modified to the following:

```
free_image(im);
memcpy(im, &resized, sizeof(image));
free_image(&part);
```

**Comment by Dynmi** [comment]
`void resize_image(image *im, int w, int h)`这个函数是对`image *im`进行处理，最后是把resized拷贝复制给im，然后resized就没用了，`free_image()`函数是释放image的内存。

**Comment by mjc0608** [comment]
可能我没仔细看，之前记得跑出了segmentation fault，然后照着上面改好了。用valgrind也跑出了一些内存问题，你有空可以试试。

**Comment by Dynmi** [comment]
> 可能我没仔细看，之前记得跑出了segmentation fault，然后照着上面改好了。用valgrind也跑出了一些内存问题，你有空可以试试。

OK。我这边再调试一下
